# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeLeastShrew < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Least Shrew")

    hg = HostGenome.new
    hg.name = "Least Shrew"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/least_shrew/2025-12-12/host-genome-generation-1/least_shrew.bowtie2.tar"
    hg.skip_deutero_filter = 1 # this is set to 1 because the host is a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Least Shrew")
    hg.destroy! if hg
  end
end
