# frozen_string_literal: true

# This file was originally auto-generated by the graphql gem.

class GraphqlController < ApplicationController
  # This is recommended by Rails documentation for request forgery
  # protection in APIs.
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user: current_user,
      current_power: Power.new(current_user),
    }
    result = IdseqSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    log_graphql_errors(result, query: query, variables: variables, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    LogUtil.log_error(
      "GraphQL execution error: #{e.message}",
      exception: e,
      query: query,
      variables: variables,
      operation_name: operation_name
    )
    raise e unless Rails.env.development?

    handle_error_in_development(e)
  end

  private

  def log_graphql_errors(result, query:, variables:, operation_name:)
    errors = result["errors"] || (result.respond_to?(:to_h) && result.to_h["errors"])
    return if errors.blank?

    errors.each do |error|
      message = error.is_a?(Hash) ? (error["message"] || error[:message]) : error.to_s
      LogUtil.log_error(
        "GraphQL error: #{message}",
        query: query,
        variables: variables,
        operation_name: operation_name,
        error: error
      )
    end
  end

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: :internal_server_error
  end
end
